# Below the expansion in cardinality and vocabulary of original 32 prompts for the class-agnostic experiment
prompts_99 = [
    "a photo of an object",
    "a photo of something natural",
    "a photo of something man-made",
    "a blurry photo",
    "a close-up photo",
    "a photo taken during the day",
    "a photo taken outdoors",
    "a photo taken indoors",
    "a small object",
    "a large object",
    "an animal",
    "a machine",
    "a thing that moves",
    "a stationary object",
    "a photo of a living thing",
    "a photo of a synthetic thing",
    "a colorful object",
    "a grayscale image",
    "a smooth surface",
    "a textured object",
    "a plastic object",
    "a metallic object",
    "a flying thing",
    "a photo of something round",
    "a rectangular object",
    "a noisy image",
    "an object with wheels",
    "an object with wings",
    "an underwater object",
    "a photo from a low angle",
    "a photo from a top view",
    "a centered object",

    # new added prompts
    "a natural landscape",
    "a photo with multiple objects",
    "an object with bright colors",
    "an old-looking object",
    "a new, modern object",
    "a shiny surface",
    "a matte texture",
    "an object in motion",
    "a photo with shadows",
    "an object casting a reflection",
    "a symmetrical object",
    "an asymmetrical object",
    "a photo with high contrast",
    "a photo with soft lighting",
    "a photo taken in a forest",
    "a photo taken near water",
    "a photo taken in a city",
    "an indoor object with artificial lighting",
    "a worn-out object",
    "a clean and polished object",
    "an object made of wood",
    "an object made of glass",
    "an object made of fabric",
    "an object with multiple textures",
    "a photo showing part of a larger structure",
    "a zoomed-out photo",
    "a zoomed-in photo",
    "an object with a face",
    "an object with visible legs",
    "a complex-shaped object",
    "a simple geometric shape",
    "a vertical object",
    "a horizontal object",
    "an object with visible patterns",
    "an object with irregular patterns",
    "an object viewed from the side",
    "an object viewed from behind",
    "a solitary object",
    "a crowded scene",
    "an object partially occluded",
    "an object with a shadow below it",
    "an object that suggests movement",
    "an object associated with nature",
    "an object associated with technology",
    "an object that could be found in a kitchen",
    "an object that could be found in a garage",
    "an object that looks soft",
    "an object that looks hard",
    "an object with holes",
    "a photo with a colorful background",
    "a photo with a neutral background",
    "a photo with abstract shapes",
    "an object with handles",
    "an object that could be picked up by hand",
    "an object larger than a person",
    "an object smaller than a hand",
    "a photo that looks artistic",
    "a technical or industrial photo",
    "an object placed on a flat surface",
    "an object suspended in air",
    "a photo where the background is blurred",
    "a photo where the object is blurry",
    "a photo where the object is sharply in focus",
    "a photo showing interaction between objects",
    "a photo of a mechanical structure",
    "a soft-edged object",
    "a hard-edged object"
]

added_prompts_106 = [
    "an object that is mostly one color",
    "an object that is multicolored",
    "a photo with a plain background",
    "a photo with a cluttered background",
    "an object near a person",
    "an object resting on another object",
    "an object casting a long shadow",
    "an object with a translucent surface",
    "an object reflecting light",
    "an object made of rubber",
    "an object made of stone",
    "an object made of paper",
    "an object that appears soft to the touch",
    "an object with visible joints",
    "an object with visible seams",
    "an object in a bright environment",
    "an object in a dim environment",
    "a photo with sharp edges and high clarity",
    "a photo with soft focus and low clarity",
    "an object surrounded by other objects",
    "an isolated object in the frame",
    "an object seen through glass",
    "an object partially hidden behind something",
    "a naturally occurring object",
    "a man-made object with smooth curves",
    "a man-made object with sharp angles",
    "a functional object",
    "a decorative object",
    "a portable object",
    "a fixed object",
    "an object hanging in the air",
    "an object resting on fabric",
    "an object on a natural surface",
    "an object in an unnatural pose or orientation",
    "an object that is symmetrical along a vertical axis",
    "an object that is symmetrical along a horizontal axis",
    "an object with circular features",
    "an object with straight lines",
    "an object with organic curves",
    "an object that looks fragile",
    "an object that looks sturdy",
    "an object in motion blur",
    "a dynamic scene",
    "a static scene",
    "an object with surface details",
    "an object with no visible details",
    "an object in front of a textured wall",
    "an object placed diagonally",
    "an object with visible writing",
    "an object with symbols or logos",
    "a reflective metallic object",
    "an object that could be used outdoors",
    "an object that belongs in an office",
    "an object with an ergonomic shape",
    "an object designed for comfort",
    "an object designed for speed",
    "an object designed for strength",
    "an object made for children",
    "an object made for adults",
    "an object with visible fasteners or screws",
    "a photo of an old-fashioned object",
    "a futuristic-looking object",
    "an object with artistic elements",
    "a utilitarian object",
    "a mechanical-looking object",
    "a nature-inspired design",
    "an object with a handle or grip",
    "an object meant to be pushed or pulled",
    "an object with a repeating pattern",
    "an object with irregular surface features",
    "an object that is part of a larger whole",
    "an object that stands on its own",
    "an object shown from an unusual angle",
    "a photo with heavy shadows",
    "a photo with even lighting",
    "an object in a transparent container",
    "an object arranged carefully",
    "an object in a random position",
    "an abstract-looking object",
    "an object with mechanical parts",
    "an object designed to float",
    "an object designed to sink",
    "an object that rolls",
    "an object that folds",
    "an object with moving parts",
    "an object designed to interact with people",
    "an object used for measurement",
    "an object used for storage",
    "an object used for decoration",
    "a photo taken at sunset",
    "a photo taken in artificial light",
    "an object partially out of frame",
    "an object with rounded corners",
    "an object with pointed edges",
    "an object with a glossy surface",
    "an object with a matte finish",
    "an object that looks familiar",
    "an object that looks unusual",
    "an object from a low-tech context",
    "an object from a high-tech context",
    "an object in a domestic setting",
    "an object in a public space",
    "an object that suggests a specific action",
    "an object used for leisure",
    "an object associated with education",
    "an object that appears aged or used"
]

added_prompts_210= [
    "a absorbent-looking object",
    "a alien-looking object",
    "a asymmetrical-shaped object",
    "a blunt-looking object",
    "a circular-looking object",
    "a compact-shaped object",
    "a construction-shaped object",
    "a cropped-shaped object",
    "a damaged-looking object",
    "a education-looking object",
    "a entertainment-looking object",
    "a first-person perspective photo",
    "a folded-looking object",
    "a futuristic-looking object",
    "a geometric-looking object",
    "a glass-made object",
    "a glossy surface photo",
    "a group interaction photo",
    "a heavy object photo",
    "a home setting photo",
    "a human interaction photo",
    "a inflatable-shaped object",
    "a industrial setting photo",
    "a jagged-shaped object",
    "a laboratory setting photo",
    "a leather-made object",
    "a light object photo",
    "a matte surface photo",
    "a mechanical interaction photo",
    "a measuring-looking object",
    "a metal-made object",
    "a minimalistic-looking object",
    "a natural interaction photo",
    "a navigation-looking object",
    "a noisy-looking object",
    "a object made of ceramic",
    "a object made of glass",
    "a object made of leather",
    "a object made of paper",
    "a object made of rubber",
    "a object made of stone",
    "a observation-looking object",
    "a office setting photo",
    "a old-looking object",
    "a organic-looking object",
    "a overhead perspective photo",
    "a paper-made object",
    "a photo from a cropped perspective",
    "a photo from a distant perspective",
    "a photo from a first-person perspective",
    "a photo from a low-angle perspective",
    "a photo from a reflected perspective",
    "a photo from a tilted perspective",
    "a photo from an obscured perspective",
    "a photo in a cluttered setting",
    "a photo in a domestic setting",
    "a photo in a industrial setting",
    "a photo in a natural setting",
    "a photo in a studio setting",
    "a photo in a urban setting",
    "a photo involving animal interaction",
    "a photo involving accidental interaction",
    "a photo involving chaotic interaction",
    "a photo involving friendly interaction",
    "a photo involving group interaction",
    "a photo involving human interaction",
    "a photo involving invisible interaction",
    "a photo involving mechanical interaction",
    "a photo involving natural interaction",
    "a photo involving routine interaction",
    "a photo of a blunt object",
    "a photo of a circular object",
    "a photo of a cracked surface",
    "a photo of a damaged object",
    "a photo of a dull surface",
    "a photo of a fuzzy surface",
    "a photo of a geometric shape",
    "a photo of a jagged surface",
    "a photo of a matte object",
    "a photo of a new object",
    "a photo of a old object",
    "a photo of a ornamental object",
    "a photo of a paper-made item",
    "a photo of a patterned surface",
    "a photo of a polished surface",
    "a photo of a porous object",
    "a photo of a rubber-made item",
    "a photo of a rural setting",
    "a photo of a sandy surface",
    "a photo of a shiny object",
    "a photo of a silent object",
    "a photo of a slimy surface",
    "a photo of a soft surface",
    "a photo of a spiral object",
    "a photo of a sticky surface",
    "a photo of a stone-made item",
    "a photo of a studio object",
    "a photo of a textile-made item",
    "a photo of a threatening object",
    "a photo of a translucent surface",
    "a photo of a transport-related object",
    "a photo of a unfamiliar object",
    "a photo of a unusual shape",
    "a photo of an absorbent object",
    "a photo of an alien shape",
    "a photo of an ergonomic design",
    "a photo of an inflatable object",
    "a photo of an irregular pattern",
    "a photo of an minimal design",
    "a photo of an object made of plastic",
    "a photo of an object on glossy surface",
    "a photo of an object used for navigation",
    "a photo of an object used for writing",
    "a photo of an reflective surface",
    "a photo of an rough surface",
    "a photo of an sharp-edged item",
    "a photo of an smooth-edged item",
    "a photo of an spiral-shaped object",
    "a photo of an symmetrical object",
    "a photo of an translucent object",
    "a photo of an wavy surface",
    "a plastic-looking object",
    "a playroom object photo",
    "a polished-looking object",
    "a portable object photo",
    "a public-space object photo",
    "a purpose-built object",
    "a reflective-looking object",
    "a rubber-made object",
    "a rural setting object",
    "a shiny-looking object",
    "a silent-looking object",
    "a simple-shaped object",
    "a soft-looking object",
    "a soft-surface object",
    "a solo interaction photo",
    "a square-shaped object",
    "a stone-looking object",
    "a studio object photo",
    "a symmetrical-shaped object",
    "a textile-looking object",
    "a thick-looking object",
    "a thin-looking object",
    "a tilted perspective photo",
    "a translucent-looking object",
    "a transport-looking object",
    "a unusual-shaped object",
    "a urban setting object",
    "an abstractly shaped object",
    "an object associated with motion",
    "an object associated with noise",
    "an object associated with routine",
    "an object associated with softness",
    "an object associated with strength",
    "an object from an alien design",
    "an object from an ergonomic perspective",
    "an object from an industrial design",
    "an object from an organic shape",
    "an object from nature",
    "an object in an artistic context",
    "an object in an chaotic context",
    "an object in an clean context",
    "an object in an colorful context",
    "an object in an geometric composition",
    "an object in an minimal setting",
    "an object in soft focus",
    "an object interacting with another object",
    "an object on an elevated surface",
    "an object on natural ground",
    "an object partially visible",
    "an object placed carefully",
    "an object placed randomly",
    "an object resting on metal",
    "an object resting on natural material",
    "an object resting on paper",
    "an object resting on plastic",
    "an object resting on textile",
    "an object seen through mist",
    "an object suspended in mid-air",
    "an object surrounded by patterns",
    "an object with bright highlights",
    "an object with color gradient",
    "an object with colored patterns",
    "an object with complex symmetry",
    "an object with decorative features",
    "an object with dirt or stains",
    "an object with distinct features",
    "an object with geometric patterns",
    "an object with glossy paint",
    "an object with high saturation",
    "an object with holes",
    "an object with matte finish",
    "an object with mixed materials",
    "an object with ornamental detail",
    "an object with primary colors",
    "an object with rough outlines",
    "an object with shadows cast",
    "an object with soft fabric",
    "an object with symmetrical balance",
    "an object with transparent parts",
    "an object with unusual design",
    "an object with visible grain",
    "an object with visible seams",
    "an object with worn edges",
    "an object without clear function",
    "an overhead view object",
    "an patterned object photo",
    "an routine interaction photo",
    "an textured object image",
    "an tilted object photo"
]
